//! Theme registration and selection.
//!
//! The palettes live in `themes/robot-whisperer.json` as a gpui-component
//! `ThemeSet`, generated by `themes/generate.py` from a small per-theme seed so
//! all seven share one elevation ramp and one set of semantics. They are
//! embedded rather than read from disk so the web build needs no asset origin.

use anyhow::{Context as _, Result};
use gpui::{App, WindowAppearance};
use gpui_component::{ActiveTheme as _, Theme, ThemeMode, ThemeRegistry};

const THEME_SET: &str = include_str!("../themes/robot-whisperer.json");

/// The designed dark theme; `is_default` in the JSON.
pub const DARK: &str = "Robot Whisperer Dark";
/// The designed light theme, used when the OS asks for light.
pub const LIGHT: &str = "Robot Whisperer Light";

/// What the user asked for, as opposed to what is currently applied.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub enum Preference {
    /// Track the OS appearance, switching between [`DARK`] and [`LIGHT`].
    #[default]
    System,
    /// Always this theme, whatever the OS says.
    Named(String),
}

impl Preference {
    /// Parses the persisted form. `"system"` is the sentinel; anything else is a
    /// theme name.
    pub fn parse(raw: &str) -> Self {
        if raw == "system" {
            Self::System
        } else {
            Self::Named(raw.to_string())
        }
    }

    /// The persisted form.
    pub fn as_str(&self) -> &str {
        match self {
            Self::System => "system",
            Self::Named(name) => name,
        }
    }
}

/// Registers the bundled themes. Call once during init, before the first window.
pub fn register(cx: &mut App) -> Result<()> {
    ThemeRegistry::global_mut(cx)
        .load_themes_from_str(THEME_SET)
        .context("bundled theme set failed to load")
}

/// Names of every bundled theme, in the order the JSON authors them.
///
/// Read from the embedded source rather than the registry, whose map does not
/// preserve order.
pub fn names() -> Vec<String> {
    #[derive(serde::Deserialize)]
    struct Named {
        name: String,
    }
    #[derive(serde::Deserialize)]
    struct Set {
        themes: Vec<Named>,
    }

    serde_json::from_str::<Set>(THEME_SET)
        .map(|set| set.themes.into_iter().map(|theme| theme.name).collect())
        .unwrap_or_default()
}

/// Applies a preference, resolving [`Preference::System`] against the OS.
pub fn apply(preference: &Preference, cx: &mut App) {
    let name = match preference {
        Preference::System => system_theme(cx.window_appearance()),
        Preference::Named(name) => name.as_str(),
    };
    apply_named(name, cx);
}

/// Which designed theme an OS appearance maps to.
fn system_theme(appearance: WindowAppearance) -> &'static str {
    if ThemeMode::from(appearance).is_dark() {
        DARK
    } else {
        LIGHT
    }
}

/// Applies one registered theme by name. Unknown names are ignored rather than
/// panicking, so a stale persisted value cannot brick startup.
fn apply_named(name: &str, cx: &mut App) {
    let Some(config) = ThemeRegistry::global(cx).themes().get(name).cloned() else {
        tracing::warn!("no theme named {name:?}; keeping the current one");
        return;
    };

    let mode = config.mode;
    Theme::global_mut(cx).apply_config(&config);
    Theme::change(mode, None, cx);
}

/// The applied theme's name, for display.
pub fn current(cx: &App) -> String {
    cx.theme().theme_name().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use gpui_component::ThemeSet;

    fn theme_set() -> ThemeSet {
        serde_json::from_str(THEME_SET).expect("bundled theme set must parse")
    }

    #[test]
    fn bundles_seven_themes_including_the_designed_pair() {
        let all = names();
        assert_eq!(all.len(), 7);
        assert!(all.contains(&DARK.to_string()));
        assert!(all.contains(&LIGHT.to_string()));
    }

    #[test]
    fn the_dark_theme_is_the_default() {
        let defaults: Vec<_> = theme_set()
            .themes
            .iter()
            .filter(|theme| theme.is_default)
            .map(|theme| theme.name.to_string())
            .collect();
        assert_eq!(defaults, vec![DARK.to_string()]);
    }

    #[test]
    fn system_appearance_picks_the_matching_designed_theme() {
        assert_eq!(system_theme(WindowAppearance::Dark), DARK);
        assert_eq!(system_theme(WindowAppearance::VibrantDark), DARK);
        assert_eq!(system_theme(WindowAppearance::Light), LIGHT);
        assert_eq!(system_theme(WindowAppearance::VibrantLight), LIGHT);
    }

    #[test]
    fn preference_round_trips_through_its_persisted_form() {
        assert_eq!(Preference::parse("system"), Preference::System);
        assert_eq!(Preference::System.as_str(), "system");
        assert_eq!(Preference::parse("Nord"), Preference::Named("Nord".into()));
        assert_eq!(Preference::Named("Nord".into()).as_str(), "Nord");
        assert_eq!(Preference::default(), Preference::System);
    }

    /// `ThemeConfigColors` has no `deny_unknown_fields` and no aliases, so a
    /// misspelled key deserialises to `None` and is silently ignored. Assert the
    /// keys the design depends on actually land in fields.
    #[test]
    fn design_critical_keys_are_recognised() {
        for theme in theme_set().themes {
            let colors = &theme.colors;
            for (label, value) in [
                ("background", &colors.background),
                ("foreground", &colors.foreground),
                ("border", &colors.border),
                ("primary.background", &colors.primary),
                ("sidebar.background", &colors.sidebar),
                ("title_bar.background", &colors.title_bar),
                ("status_bar.background", &colors.status_bar),
                ("tab.active.background", &colors.tab_active),
                ("popover.background", &colors.popover),
                ("group_box.background", &colors.group_box),
                ("list.hover.background", &colors.list_hover),
                ("danger.background", &colors.danger),
                ("success.background", &colors.success),
                ("warning.background", &colors.warning),
                ("selection.background", &colors.selection),
                ("drop_target.background", &colors.drop_target),
                ("scrollbar.thumb.background", &colors.scrollbar_thumb),
            ] {
                assert!(
                    value.is_some(),
                    "theme {:?} did not populate {label}: the JSON key does not \
                     match the serde rename, so it is silently ignored",
                    theme.name
                );
            }

            // The request-kind colours are private fields, so they are checked
            // through the serialised form — which also proves the rename holds.
            //
            // Every base slot `tokens::kind_color` reads has to be here. A slot
            // the app reads and no theme emits does not fail loudly: it falls
            // back to the library's own palette and quietly stops following the
            // theme, which is how `base.yellow` went unnoticed for seven themes.
            //
            // Checked for a *value*, not for the key. `ThemeConfigColors`
            // serialises every one of its fields, so an unset slot is present
            // as `null` and `contains_key` says yes to all of them — which is
            // why the earlier version of this assertion passed for colours no
            // theme had ever declared.
            let round_tripped = colours(&theme);
            for key in ["base.blue", "base.green", "base.magenta", "base.yellow"] {
                assert!(
                    round_tripped
                        .get(key)
                        .and_then(serde_json::Value::as_str)
                        .is_some(),
                    "theme {:?} does not declare {key}, so it silently falls back \
                     to the library palette",
                    theme.name
                );
            }
        }
    }

    #[test]
    fn every_theme_sets_the_density_knobs() {
        // Left unset, these fall back to library defaults: square corners, no
        // shadow, 16px text — which is exactly how the first pass looked.
        for theme in theme_set().themes {
            assert_eq!(theme.radius, Some(10), "{:?} radius", theme.name);
            assert_eq!(theme.radius_lg, Some(14), "{:?} radius.lg", theme.name);
            assert_eq!(theme.shadow, Some(true), "{:?} shadow", theme.name);
            assert_eq!(theme.font_size, Some(14.0), "{:?} font.size", theme.name);
        }
    }

    #[test]
    fn colours_are_hex_with_optional_alpha() {
        for theme in theme_set().themes {
            for (key, value) in colours(&theme) {
                let Some(text) = value.as_str() else { continue };
                assert!(
                    text.starts_with('#') && matches!(text.len(), 7 | 9),
                    "theme {:?} key {key} has {text:?}",
                    theme.name
                );
            }
        }
    }

    /// A theme's colours as the map its JSON declares, which is the only way to
    /// reach the keys `ThemeConfigColors` keeps private.
    fn colours(theme: &gpui_component::ThemeConfig) -> serde_json::Map<String, serde_json::Value> {
        match serde_json::to_value(&theme.colors).expect("colors serialise") {
            serde_json::Value::Object(map) => map,
            other => panic!("expected an object, got {other}"),
        }
    }

    fn surface(theme: &gpui_component::ThemeConfig, key: &str) -> f32 {
        let colours = colours(theme);
        let hex = colours
            .get(key)
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("theme {:?} has no {key}", theme.name));
        luminance(hex)
    }

    /// Relative luminance of a `#rrggbb` colour, kept on the 0–255 scale the hex
    /// uses so a threshold reads as "how many levels apart".
    fn luminance(hex: &str) -> f32 {
        let channel =
            |at: usize| u8::from_str_radix(&hex[at..at + 2], 16).expect("two hex digits") as f32;
        0.2126 * channel(1) + 0.7152 * channel(3) + 0.0722 * channel(5)
    }

    /// The surfaces have to be far enough apart to *see*.
    ///
    /// The first designed ramp stepped 11 → 16 → 20 → 26 out of 255 and looked
    /// entirely flat on a real display, and the light palette had its card and
    /// its subtle surface both at pure white, which made every card header and
    /// hover state invisible. Neither showed up in any assertion, so both are
    /// asserted now.
    #[test]
    fn the_elevation_ramp_is_visible_on_every_theme() {
        /// Levels of luminance, out of 255, that two adjacent surfaces need.
        const STEP: f32 = 5.0;

        for theme in theme_set().themes {
            let window = surface(&theme, "background");
            let panel = surface(&theme, "sidebar.background");
            let card = surface(&theme, "group_box.background");
            let subtle = surface(&theme, "muted.background");

            for (from, to, step) in [
                (window, panel, "window → panel"),
                (panel, card, "panel → card"),
                // The subtle surface carries hover states, card headers and quiet
                // tiles, so it has to leave the card in whichever direction the
                // palette has room for.
                (card, subtle, "card → subtle"),
            ] {
                assert!(
                    (to - from).abs() >= STEP,
                    "theme {:?}: {step} differ by {:.1} levels, need {STEP}",
                    theme.name,
                    (to - from).abs()
                );
            }
        }
    }

    /// A border a few levels from the surface it edges is not a border.
    #[test]
    fn borders_read_against_the_surfaces_they_edge() {
        const STEP: f32 = 8.0;

        for theme in theme_set().themes {
            let border = surface(&theme, "border");
            let card = surface(&theme, "group_box.background");
            assert!(
                (border - card).abs() >= STEP,
                "theme {:?}: border is {:.1} levels from the card surface",
                theme.name,
                (border - card).abs()
            );
        }
    }

    #[test]
    fn both_modes_are_represented() {
        let set = theme_set();
        assert!(set.themes.iter().any(|theme| theme.mode.is_dark()));
        assert!(set.themes.iter().any(|theme| !theme.mode.is_dark()));
    }
}
